### PR TITLE
Feature/create table attendance

### LINKED ISSUE #8: attendance_table
# Requirements
- As an employee, I want to check-in / check-out  to register my attendance

### PR DESCRIPTION
**Pull request by PudinDeveloper**
# Description
### What did you implemented/Why did you implemented this:
 - Create table assistance to register employee´s check-in and check-out.
 - Add relation between stores_table and attendance_table to have access in code.
 - Fix a bug related to check-in where datetimes were incorrect.
 - Change Ruby version to 3.0.0.
 - Add relations between models attendance with employee and store models.
 - Add Seeder to initialize the database with random data.

### Examples:
 - Seeder data contains fake information.
 - Relations improve the database information access.
 - Datetime of check-in is related to the time-zone.

### CODE REVIEW

**Review by HopeSaurus — APPROVED** [review]
Its all good, nice work

**Review by EduardoBriceno89 — APPROVED** [review]
Looks good to me. keep up the good work!!!

**Review by cuzo24 — APPROVED** [review]
Everything looks ok

**Review by willcab — APPROVED** [review]
LGTM

**Pull request merged**
