### PR TITLE
Add employee list p/store

### LINKED ISSUE #19: feature#19-employees-of-each-store
As an admin I want to see which employees are from a store with a table when I see the store.

### PR DESCRIPTION
**Pull request by PudinDeveloper**
Co-authored-by: CalixtoLopez <calixto.lopez.santos@gmail.com>
Co-authored-by: GustavoHiguera  <ghiguera@ucol.mx>
Co-authored-by: JorgeRodz <jarf4321@gmail.com>

# Description
-  Add table in each store that shows employees working in that specific store.

# Screenshot
image
image

### CODE REVIEW

**Comment by JuanequeX** [comment]
The co-authors on your description are necessary at this step

**Review by JuanequeX — APPROVED** [review]
LGTM

**Review by EduardoBriceno89 — APPROVED** [review]
Nice design, good work!!!

**Review by elioflo — APPROVED** [review]
Good job!

**Pull request merged**
