### PR TITLE
Create - stores crud: controller, views and routes

### LINKED ISSUE #5: stores_CRUD
# Requirements:
- As an admin, I want to create, read, update and delete stores with an interface.

### PR DESCRIPTION
**Pull request by JorgeRodz**
# Description
- Create basic 'store CRUD' in order to manage the data.
- No style yet implemented.

 Examples:
 - We now can display all the stores
 - Create/Update stores

  ## Screenshots
image
image
image
image

### CODE REVIEW

**Review by HopeSaurus — APPROVED** [review]
Everything's A-OK

**Review by jorgeboris — APPROVED** [review]
Lgtm 👍🏻

**Review by EduardoBriceno89 — APPROVED** [review]
Looks nice, keep doing a great job!!!

**Comment by iMartinDav** [comment]
Good

**Review by cuzo24 — APPROVED** [review]
Keep up the good work!

**Review by willcab — APPROVED** [review]
LGTM

**Review by iMartinDav — COMMENTED** [review]
Good: “The concurrency model here is adding complexity to the system without any actual performance benefit that I can see.

**Pull request merged**
